// Keep this small-ish; you can move big blobs to JSON if you prefer.
export type ContentBundle = {
  projects: any[]; experiences: any[]; journey: any[]; notes: any[]; products: any[];
};

const uid = () => Math.random().toString(36).slice(2, 10);

// SEED, unchanged (trimmed here for brevity)
export const DEFAULT_CONTENT: ContentBundle = {
  projects: [
    {
      id: uid(),
      title: 'Auprea Heritage for everyone',
      description: 'Wealth manager with secure vault, PDF declarations, and an optional notary flow.',
      logoUrl: '/images/auprea.ico',
      url: '',
      tags: ['saas', 'client'],
      tech: ['Next.js', 'Laravel APIs', 'PDF'],
      metric: 'Net worth in minutes',
      caseFile: {
        problem: 'Users tracked assets in spreadsheets without a unified net-worth view or safe document storage.',
        approach: [
          'Domain model for assets/liabilities; secure doc vault w/ role-based access',
          'Server-generated PDF declarations; optional notarization workflow',
          'Performance budget for dashboard—<150ms TTFB on cached pages',
        ],
        result: 'Single source of truth; faster onboarding; exportable declarations that are legally tidy.',
        images: [
          { src: '/case/auprea-dashboard.jpg', alt: 'Auprea dashboard' },
          { src: '/case/auprea-vault.jpg', alt: 'Auprea document vault' },
        ],
        tags: ['saas', 'finance'],
        tech: ['Next.js', 'Laravel', 'MySQL', 'S3'],
      },
    },
  ],
  experiences: [
    {
      id: uid(),
      title: 'Banking API Integration',
      job: 'Financial Software Engineer',
      fromTo: 'Sept. 2024 ~ Mar 2025 · 7 months',
      bullets: [
        'Built Laravel API integrating bank transactions',
        'Livewire-powered financial reporting and reconciliation',
      ],
      type: 'Freelance',
    },
  ],
  journey: [
    {
      id: uid(),
      kind: 'education',
      year: '2024 ~ Present',
      title: 'Bachelor’s – Software Engineering / Computer Science (Ongoing)',
      org: 'KeMU',
      url: 'https://www.kemu.ac.ke/',
      note: 'Systems design, cloud, AI, security',
    },
    {
      id: uid(),
      kind: 'cert',
      year: '2024',
      title: 'Hosting & Server Management (cPanel Certified)',
      org: 'cPanel University',
      url: 'https://university.cpanel.net/',
    },
  ],
  notes: [
    {
      id: uid(),
      slug: 'shipping-saas-like-an-ops-team',
      title: 'Shipping SaaS like an ops team',
      excerpt: 'Treat features like on-call: runbooks, budgets, dashboards first—then UI.',
      cover: '/blog/ops-saas.jpg',
      date: '2025-07-20',
      reading: '6 min',
      tags: ['saaS', 'process', 'devops'],
    },
  ],
  products: [
    {
      id: uid(),
      slug: 'saas-starter-kit',
      title: 'SaaS Starter Kit',
      tagline: 'Ship your SaaS in days, not months',
      description: 'A production-ready Next.js 14 boilerplate with authentication, billing, admin dashboard, and everything you need to launch fast.',
      category: 'platform',
      price: 149,
      currency: 'USD',
      priceLabel: 'one-time',
      status: 'published',
      features: [
        'Next.js 14 App Router + TypeScript',
        'NextAuth with Google & GitHub providers',
        'Prisma + PostgreSQL schema',
        'Stripe subscriptions + one-time payments',
        'Admin CMS dashboard',
        'Tailwind CSS + shadcn/ui',
        'Email transactional templates',
        'Deploy-ready for Vercel + Railway',
      ],
      tags: ['next.js', 'saas', 'starter', 'typescript'],
      cover: '/shop/saas-starter.jpg',
      demoUrl: '',
      buyUrl: '',
    },
    {
      id: uid(),
      slug: 'api-integration-playbook',
      title: 'API Integration Playbook',
      tagline: 'From zero to production API in one weekend',
      description: 'A comprehensive guide covering REST, webhooks, OAuth, rate limiting, and real-world integration patterns with Laravel and Next.js examples.',
      category: 'document',
      price: 29,
      currency: 'USD',
      priceLabel: 'one-time',
      status: 'published',
      features: [
        '80+ pages of practical guidance',
        'REST & GraphQL patterns',
        'OAuth 2.0 deep dive',
        'Webhook design & retry logic',
        'Rate limiting strategies',
        'Laravel + Next.js code examples',
        'Postman collection included',
      ],
      tags: ['api', 'laravel', 'rest', 'guide'],
      cover: '/shop/api-playbook.jpg',
      demoUrl: '',
      buyUrl: '',
    },
    {
      id: uid(),
      slug: 'deployment-optimization',
      title: 'Deployment & Optimization',
      tagline: 'Your app, production-hardened',
      description: 'A hands-on service to audit, optimize, and deploy your web application. Covers CI/CD setup, performance tuning, database indexing, and infrastructure provisioning.',
      category: 'service',
      price: 499,
      currency: 'USD',
      priceLabel: 'starting at',
      status: 'published',
      features: [
        'Full app performance audit',
        'CI/CD pipeline setup (GitHub Actions)',
        'Docker + VPS or cloud deployment',
        'Database query optimization',
        'Caching strategy (Redis/CDN)',
        'SSL, security headers, rate limiting',
        '30-day post-deployment support',
      ],
      tags: ['devops', 'deployment', 'performance', 'service'],
      cover: '/shop/deployment.jpg',
      demoUrl: '',
      buyUrl: '',
    },
  ],
};
